options:
  logging: CLOUD_LOGGING_ONLY    # <── add this block (2 spaces indent)

steps:
  - id: "Terraform Init & Apply"
    name: "hashicorp/terraform:1.7"
    entrypoint: "/bin/sh"
    args:
      - "-c"
      - |
        cd infra
        terraform init
        terraform apply -auto-approve -input=false
timeout: "1200s"
