options:
  logging: CLOUD_LOGGING_ONLY      # keep this

steps:
  - id: Terraform Init & Apply
    name: hashicorp/terraform:1.7
    entrypoint: sh
    args:
      - -c
      - |
        terraform init -input=false -reconfigure
        terraform apply -auto-approve -input=false
timeout: "1200s"
